### PR TITLE
It was said that "English" is never mentioned.

### PR DESCRIPTION
**Pull request by madvorak**

### CODE REVIEW

**Comment by mmasdeu** [comment]
I'm fine with the change. The course was fully in Catalan, but the game is 100% in English so fair to have both tags.

**Comment by madvorak** [comment]
Well, course in Catalan, even if all materials are in English, qualifies as a course in Catalan.

**Comment by PatrickMassot** [comment]
I don't see the point of the Catalan tag if all the publicly available files are fully in English. This tag is meant to help people who look for resources in non-English languages and to warn people who are looking for English resources.

**Comment by mmasdeu** [comment]
I thought that this page was meant as a device to record the different courses that were taking place everywhere. One of its uses is to access the course materials themselves, but there may be other uses. What if some day one wants to say: Lean has been taught at N universities across the globe, in M languages and wants to get the values of N and M from this page?

**Pull request closed without merging**
