### PR TITLE
Promote `lean project" to it's own section on install pages

### PR DESCRIPTION
**Pull request by shingtaklam1324**
Right now it's just a line at the end and it's quite easy to miss. Making it its own section should make it more noticeable.

### CODE REVIEW

**Comment by PatrickMassot** [comment]
Thanks. I think this is a good idea but I'm not sure about the title of that section, since it refers to explanations about both creating a project and working on an existing ones. We could expand the title but it would probably become too long, so it may be better the shorten it to `Lean projects`. I don't have strong feelings here anyway, so I'll let other people comment. Anything that make this link more visible is welcome.

**Comment by PatrickMassot** [comment]
@shingtaklam1324?

**Comment by shingtaklam1324** [comment]
(I don't check really GitHub notifications, if you want to mention me it may be better to ping me on Zulip)

I think it'd make sense to change it to `Lean projects`. I think rolling back the last commit should do. 

However there's now a merge conflict with the MacOS file which seems to have been changed. What should I do about that?

**Comment by bryangingechen** [comment]
> However there's now a merge conflict with the MacOS file which seems to have been changed. What should I do about that?

Type `git merge origin/newsite` in your command line, then [fix the conflict in your text editor](https://git-scm.com/book/en/v2/Git-Branching-Basic-Branching-and-Merging#_basic_merge_conflicts). 

In this case, it might be easiest to just replace `templates/install/macos.md` with the current contents and then add the section heading to the end of that file.

Note that there's now also a new file `templates/install/macos_details.md` with the contents of the old `templates/install/macos.md` file, and you should make your changes there too.

**Comment by shingtaklam1324** [comment]
Alright, I'm doing it on a fork of mine and I'm really struggling with git. Would it just be easier for me to close this and work on a fresh fork?

**Comment by bryangingechen** [comment]
Whatever you're most comfortable with! (It's well-worth learning how to deal with merge conflicts though. Feel free to ask for help on Zulip.)

**Comment by shingtaklam1324** [comment]
Ok I've fixed all the git issues, and I've changed the titles to `Lean Projects`

**Comment by PatrickMassot** [comment]
Why did you change the sentence? The new one has a lot of "now".

**Comment by shingtaklam1324** [comment]
That was the sentence in the original commit. I'll revert those changes and use the original sentences.

**Comment by PatrickMassot** [comment]
Thanks!

**Pull request merged**
