### PR TITLE
display decl counts on stats page

### PR DESCRIPTION
**Pull request by robertylewis**
image

### CODE REVIEW

**Comment by robertylewis** [comment]
(CI should pass after the next docs build.)

**Comment by bryangingechen** [comment]
Do we want to make graphs of these too?

**Comment by robertylewis** [comment]
> Do we want to make graphs of these too?

This is much harder than the other graphs since each data point takes a compiled mathlib to calculate. It's far too expensive to regenerate the whole data set each time, like gitstats does for the others. We'd need to add points incrementally and store a cache somewhere. And seeding the first one will take a huge amount of time. Let's say 2.5 years before we started storing olean caches, one data point a day instead of per commit like gitstats, 15 min per build average (older ones were faster). That's 10 days of computing -- better parallelize that!

**Comment by bryangingechen** [comment]
Ah, OK. I'm not sure we have to have data points for all the old commits for a graph to be useful, but there are some other interesting things we might want to compute from each mathlib commit (like the type class graph and maybe some statistics on that), so maybe we can look into a unified way of caching the history of those later on.

**Comment by PatrickMassot** [comment]
I'm on vacation this week. Both my computer at home and my office computer are idle (and fast). If you give me scripts to run I'd be happy to help.

**Comment by PatrickMassot** [comment]
And of course we could restrict to one data point per week in the archive.

**Comment by robertylewis** [comment]
The script is nontrivial and there's the issue of where to store the cached results, which is going to force some annoying Actions wrangling. I can't say I'm excited about doing this just to produce a graph which, I predict, will be a slightly flatter version of the LOC graph. If someone wants to do this I certainly won't stop them but I can't justify the effort myself.

**Pull request merged**
