### PR TITLE
feat(templates/install): warning for distro package managers

### PR DESCRIPTION
**Pull request by lambda-fairy**
It's implied by the rest of the docs, but I think it's worth making it explicit, given how often the problem appears on Zulip.

### CODE REVIEW

**Comment by kbuzzard** [comment]
Maybe you should add that at the time of writing lean is making new releases every few weeks, so it's highly likely that the version in your package manager is already out of date?

**Comment by lambda-fairy** [comment]
Thanks @kbuzzard, added.

Also added a note about elan handling multiple versions. (I hedged my point with "most" to placate the Nix fans)

**Comment by PatrickMassot** [comment]
I don't understand the placement of those paragraph, and I don't understand the last sentence. 

And I'm skeptical about the general idea. People who arrive at those web page already decided they were not using their package managers.

**Comment by jcommelin** [comment]
I agree with Patrick that I don't understand the last sentence.

Otoh, I don't think it hurts to add this warning: I often skim install pages in combination with installation via distro package managers.

**Comment by PatrickMassot** [comment]
I am closing this since it did not converge.

**Pull request closed without merging**
