### PR TITLE
lean-web-editor

### PR DESCRIPTION
**Pull request by bryangingechen**
@cipher1024 suggested that I PR [my version of the lean-web-editor](https://github.com/bryangingechen/lean-web-editor) here. 

Thanks to @semorrison for kindly agreeing to host the emscripten files and the zip bundle that the web editor relies on!

### CODE REVIEW

**Comment by semorrison** [comment]
Hi @bryangingechen, could you quickly explain where this will end up deployed?

**Comment by bryangingechen** [comment]
Sure, I think it should end up at https://leanprover-community.github.io/lean-web-editor

**Comment by bryangingechen** [comment]
Oh wait, do I need to do something with the jekyll config to get this to work?

**Comment by robertylewis** [comment]
Thanks! This looks nice. When I test it locally, Lean runs extremely slowly. (The editor is perfectly responsive, but it takes ages to check a few lines.) Any idea why?

I suppose we can just merge and test it in production.

**Comment by robertylewis** [comment]
The production version is much faster. Not sure what the difference is!

**Comment by bryangingechen** [comment]
Strange - I'm getting CORS errors for the file https://tqft.net/lean/web-editor/lean_js_wasm.wasm when I visit https://leanprover-community.github.io/lean-web-editor. Following up with @semorrison on Zulip...

**Comment by cipher1024** [comment]
Is there a way to make several versions available?

**Comment by bryangingechen** [comment]
Several versions of community Lean? Yes, but it would take some work. What did you have in mind?

**Pull request merged**
