### PR TITLE
Link to mathlib4 decls in undergrad/overview/100 theorems

### PR DESCRIPTION
**Pull request by eric-wieser**
Depends on:
* https://github.com/leanprover-community/mathlib4/pull/6043

### CODE REVIEW

**Comment by PatrickMassot** [comment]
@eric-wieser in case you didn't notice, this PR doesn't build. But thanks anyway!

**Comment by eric-wieser** [comment]
I wrote a message to that effect on Zulip: we also need to export the line number information.

**Comment by eric-wieser** [comment]
@PatrickMassot, this is now green. Happy to test in prod? Unfortunately after repeated crashes I'm hitting github rate limit errors, so can't test locally any further today.

**Review by robertylewis — APPROVED** [review]
LGTM!

**Pull request merged**
