### PR TITLE
Update the macOS detailed install instructions to recommend Homebrew.

### PR DESCRIPTION
**Pull request by Julian**
Corresponds with leanprover-community/mathlib-tools#108.

### CODE REVIEW

**Comment by FrederickGeek8** [comment]
Does it make sense to add the steps
```bash
elan toolchain install stable
elan default stable
```
since they are _also_ executed by the install script and necessary for a first-time install?

**Comment by Julian** [comment]
Yes! Good point, will add.

**Comment by Julian** [comment]
@FrederickGeek8 care to leave an lgtm here too if you agree with these changes?

@semorrison or @bryangingechen perhaps one of you two are OK with this at this point as well?

**Comment by bryangingechen** [comment]
I'd like to test this, but I installed `elan` and `mathlibtools` manually a while back. Is it worth adding instructions on how to cleanly uninstall those and switch to the `homebrew` method?

**Comment by bryangingechen** [comment]
You mentioned on Zulip that these instructions work for M1 Macs as well? Is that worth mentioning explicitly somewhere in the docs?

**Comment by Julian** [comment]
Thanks!

> I'd like to test this, but I installed elan and mathlibtools manually a while back. Is it worth adding instructions on how to cleanly uninstall those and switch to the homebrew method?

Definitely, will do in a bit (let me know if you see a decent place to add this, otherwise the best I see at the minute is tacking it to the bottom of one of these two pages).

> You mentioned on Zulip that these instructions work for M1 Macs as well?

Only the `leanproject` / mathlibtools part unfortunately. Provisioning lean / elan still will not, so it's only half this page that's relevant. I filed leanprover-community/mathlib-tools#107 with an idea for how to automate M1s as well, certainly would love your thoughts there -- either way I suspect an M1-specific section may be necessary for the detail page here. I'd personally probably not block updating the page on that given I have so little time to commit at the minute to getting that ticket done (even if you agree with the proposal), but obviously happy to do so if you think it's best.

**Comment by bryangingechen** [comment]
> Only the `leanproject` / mathlibtools part unfortunately. Provisioning lean / elan still will not, so it's only half this page that's relevant. I filed [leanprover-community/mathlib-tools#107](https://github.com/leanprover-community/mathlib-tools/issues/107) with an idea for how to automate M1s as well, certainly would love your thoughts there -- either way I suspect an M1-specific section may be necessary for the detail page here. I'd personally probably not block updating the page on that given I have so little time to commit at the minute to getting that ticket done (even if you agree with the proposal), but obviously happy to do so if you think it's best.

OK, that sounds reasonable to me. Do you think it'd be a good idea to point M1 Mac users to [the Zulip thread](https://leanprover.zulipchat.com/#narrow/stream/113489-new-members/topic/M1.20macs) in the meantime?

**Comment by FrederickGeek8** [comment]
@Julian lgtm :)

**Comment by bryangingechen** [comment]
@Julian I tested the instructions and everything seems to work great. I'm happy to merge now if you're done, though I still think some kind of note for M1 Mac users might be helpful.

**Comment by Julian** [comment]
Addressing your M1 note suggestion was on my todo before calling it done, yeah, happy to of course, though glad to hear it works and looks good!

I'll add that in a few minutes.

**Comment by Julian** [comment]
OK, done!

**Comment by bryangingechen** [comment]
Thanks so much!

**Pull request merged**
