### PR TITLE
feat: changes to the learn page

### PR DESCRIPTION
**Pull request by fpvandoorn**
* Add `Formalising Mathematics` book
* Add `The Hitchhiker's Guide to Logical Verification` book (this should not go under `(Meta)-programming and tactic writing` since it's still about proving, not programming).
* Change description of `Theorem Proving in Lean`
* Remove meetings that were not aimed at beginners, but link to the event page.

### CODE REVIEW

**Comment by fpvandoorn** [comment]
Should I also add [How to Prove it With Lean](https://djvelleman.github.io/HTPIwL/How-To-Prove-It-With-Lean.pdf)?

**Comment by kbuzzard** [comment]
I guess the CI failure is https://github.com/microsoft/linux-package-repositories/issues/130 which should be fixed now. The changes look fine to me. Why are you deleting some but not all of the pre-2022 conferences?

**Comment by fpvandoorn** [comment]
I kept the meetings that were aimed at beginners, and removed the ones that weren't. We can remove more if you think that is appropriate.

**Comment by kbuzzard** [comment]
I made a suggestion about changing the description of my notes to course notes rather than a book, but other than that this looks good to me. Are you happy with the change? If so we can merge this.

**Comment by kbuzzard** [comment]
Thanks!

**Pull request merged**
