### PR TITLE
LaTeX/Overview: Add it with macros & examples

### PR DESCRIPTION
**Pull request by RaitoBezarius**
It brings LaTeX to the list! With macros support.

### CODE REVIEW

**Comment by PatrickMassot** [comment]
I don't think we really need a  javascript loop to define five macros, but that probably doesn't hurt.

**Comment by RaitoBezarius** [comment]
> I don't think we really need a javascript loop to define five macros, but that probably doesn't hurt.
Except the fact that it's might be indeed longer than to just type five times the same macros. Size/performance issues are negligible and I was a bit lazy :c (okay that's not an excuse).

**Comment by RaitoBezarius** [comment]
Conflicts resolved.

**Comment by RaitoBezarius** [comment]
Conflicts resolved.

**Pull request merged**
