### PR TITLE
Dependencies: Add a requirements.txt for Python

### PR DESCRIPTION
**Pull request by RaitoBezarius**
That's nicer for newcomers. :-)

Ideally, I'd like to add some Nix-based stuff but that might be too much, that could be optional though.
That'd arguably nice for `bibtool` (which is packaged https://nixos.org/nixos/packages.html?attr=bibtool&channel=nixos-20.03&query=bibtool)

### CODE REVIEW

**Comment by PatrickMassot** [comment]
Thanks, but I don't see the point of pinning versions. Why not using inequalities here?

**Comment by RaitoBezarius** [comment]
For patch versions? Sure, but we don't want non-reproducible dependencies,
that's better than non-pinned versions, right?

**Comment by PatrickMassot** [comment]
You can replace all equalities by `>=` and when a new version breaks backward compatibility we fix it. We don't want to force people to have old versions around when new versions would work just fine. 

Remember also this is not a user facing python script, it is mostly used by CI and a handful of people.

**Comment by RaitoBezarius** [comment]
Indeed :)
I'll replace those!

**Comment by RaitoBezarius** [comment]
I replaced == by ≥ @PatrickMassot

**Pull request merged**
