### PR TITLE
Add course at TU Dresden to courses.yaml

### PR DESCRIPTION
**Pull request by marcusrossel**

### CODE REVIEW

**Comment by robertylewis** [comment]
Thanks! The description on the website you link to says that the course will use Haskell and Coq; is this outdated? Are there any public materials for your course you're able to share?

**Comment by marcusrossel** [comment]
@robertylewis Yes, the description is outdated. We use Lean and Coq for the exercises. Unfortunately the lecture slides and exercises are in private repositories. I'll ask the lecturer if he'd be willing to share some version of them.

**Comment by PatrickMassot** [comment]
@marcusrossel any update here?

**Comment by marcusrossel** [comment]
@sertel, could you create a new public repo from the `no-solution` branch of the `fcplcd-exercises` repo? Then I could link to the exercise sheets.

**Comment by marcusrossel** [comment]
Ok, I don't want to keep this open any longer. Sorry for the noise.

**Pull request closed without merging**
