### PR TITLE
fix: fields of ThousandPlusTheorem

### PR DESCRIPTION
**Pull request by grunweg**
Proper fix for #559: depends on leanprover-community/mathlib4#20066

### CODE REVIEW

**Comment by grunweg** [comment]
CC @bryangingechen @fpvandoorn

**Review by fpvandoorn — APPROVED** [review]
Please ping here after Mathlib PR is merged

**Comment by bryangingechen** [comment]
Looks like the mathlib PR has been merged, so I'll merge this now, thanks!

**Comment by grunweg** [comment]
Thanks!

**Comment by bryangingechen** [comment]
Ah, the buld is still broken I guess because doc-gen4 hasn't run yet. I'll retrigger the website build once that has gone through.

**Pull request merged**
