### PR TITLE
add Google authentication

### PR DESCRIPTION
**Pull request by robertylewis**
This makes Google happier about indexing and lets us see some basic stats.

### CODE REVIEW

**Comment by robertylewis** [comment]
If we want more interesting stats, we could add analytics tracking to each page. Interesting or invasive?

**Comment by jcommelin** [comment]
I would like to avoid google analytics. I'm hoping that once the student project on the search bar is done, we could get rid of all ties to google.

**Comment by robertylewis** [comment]
That's fair. I think this is worth doing anyway. It has no effect on the user side, just tells Google that we're "official" and lets us point to site maps and such.

**Comment by bryangingechen** [comment]
As Rob says, this verification is independent of Google Analytics. [Here's a page on the Google site verification](https://support.google.com/webmasters/answer/9008080?hl=en). It's mainly used in relation to the [Google search console](https://support.google.com/webmasters/answer/9128668?hl=en&ref_topic=9128571).

**Comment by gebner** [comment]
Johan and I were commenting on Rob's proposal to add Google analytics (the javascript) to each page.  I am happy with this PR.

**Comment by jcommelin** [comment]
Yup, I'm also fine with this PR.

**Pull request merged**
